### PR TITLE
Fix spc import only imports channel 0.

### PR DESCRIPTION
**Pull request by AndreasSchoenle**
Seems like `int(byte1[0:4],2)` is the channel number and the elif would ignore all counts not in channel 0.

### CODE REVIEW

**Comment by dwaithe** [comment]
Hi, I have addressed this independently.

**Comment by AndreasSchoenle** [comment]
Thanks but see my comment to 0fbb9e374bff3935bf9e211fc5d377c4ff669de1.

**Comment by dwaithe** [comment]
Hi Andreas, 
Ok, I've added in the feature. I am just a bit concerned it may crash the software later on. The software at this time only supports 2 channel data. If you have any data with 3 or more active channels I would be interested to test them on the system and come up with a solution for handling multi-channel (2+ channels). Thanks for your interest and input.

**Comment by AndreasSchoenle** [comment]
Thanks a lot! 
Most actual measurements occupy only 2 of the 4+ detector channels simultaneously, just that they are not necessarily channels 1+2. 

You could limit the channel number to < 8 or < 16 in all readers, maybe issuing a warning in case the file format allows larger channel numbers but you do not support it. You could also limit the number of simultaneously used channels and/or allow specification of the two channels you want to keep in the UI. For testing you could than hack in a routine that distributes 1-channel data over a given or random set of channels within channels 1-N? 
All analysis can readily be tested with this method in place - you know exactly how x-correlation should look w.r.t. the auto-correlation.

Thanks again and best regards!

**Pull request closed without merging**
